[package]
name = "helix-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "helix_chain"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
async-trait = "0.1"
thiserror = "1.0"
anyhow = "1.0"
rand = "0.8"
sha2 = "0.10"
sha3 = "0.10"
hex = "0.4"
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.30", features = ["bundled"] }
reqwest = { version = "0.11", features = ["json"] }
secp256k1 = { version = "0.27", features = ["rand"] }
sysinfo = "0.29"
flate2 = "1.0"
config = "0.13"

# Kriptografik bağımlılıklar
blake2 = "0.10"
base58 = "0.2"
ripemd = "0.1"
hmac = "0.12"
pbkdf2 = "0.12"
aes-gcm = "0.10"
curve25519-dalek = { version = "4.1", features = ["serde"] }
ed25519-dalek = "2.1"
x25519-dalek = "2.0"
bulletproofs = "2.0"
merlin = "3.0"
ristretto255 = "0.1"
zeroize = "1.6"
subtle = "2.5"

# WASM ve Akıllı Kontrat bağımlılıkları
wasmer = "3.0"
wasmer-compiler = "3.0"
wasmer-compiler-cranelift = "3.0"
wasmer-engine-universal = "3.0"
wasmer-types = "3.0"
wasmparser = "0.100"
wasm-encoder = "0.20"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
wat = "1.0"
wabt = "0.10"
parity-wasm = "0.42"
wasm-gc = "0.1"
wasm-opt = "0.1"
wasm-pack = "0.12"
wasm-bindgen-test = "0.3"

# Orakl bağımlılıkları
quick-xml = "0.31"
csv = "1.3"
url = "2.5"
http = "1.0"
bytes = "1.5"
async-stream = "0.3"
futures-util = "0.3"
pin-project = "1.1"
tokio-util = { version = "0.7", features = ["codec"] }
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
h2 = "0.3"
tower-service = "0.3"
tower-layer = "0.3"
tower-load = "0.3"
tower-buffer = "0.3"
tower-timeout = "0.3"
tower-retry = "0.3"
tower-limit = "0.3"
tower-balance = "0.3"
tower-discover = "0.3"
tower-hedge = "0.3"
tower-load-shed = "0.3"
tower-rate-limit = "0.3"
tower-util = "0.3"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
test-case = "3.3"
criterion = "0.5"
tempfile = "3.8"
wiremock = "0.5" 