[network]
chain_id = "helix_testnet"
listen_addr = "0.0.0.0"
listen_port = 8080
max_peers = 50
bootstrap_nodes = []

[consensus]
min_validators = 3
block_time_ms = 2000
max_block_size = 1048576  # 1MB
min_stake = 1000000000000

[database]
url = "postgres://localhost/helix"
max_connections = 10
timeout_seconds = 30

[api]
port = 5000
rate_limit_per_minute = 100
max_request_size = 1048576  # 1MB

[security]
enable_audit = true
max_failed_attempts = 5
blacklist_duration_hours = 24

[wallet]
seed = "test_seed_do_not_use_in_production"
derivation_path = "m/44'/60'/0'/0/0"
